#!/bin/bash

git submodule update --init --recursive
npm install
cd mootools-microsite
npm install
cd ../prime-website
echo "Setting up prime-website"
npm install
node docs/build
cd ../elements-website
echo "Setting up elements-website"
npm install
node docs/build
cd ..
npm install

echo "now run 'node index'"
