#! /bin/sh
### BEGIN INIT INFO
# Provides:          mootools-website
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop MooTools Website Node process
### END INIT INFO

# Author: MooTools Team <info@mootools.net>

# Do NOT "set -e"

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="MooTools Website Node process"
NAME=mootools-website
SHORTNAME=website

SOCKET=/var/opt/mootools/sockets/$SHORTNAME
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

DAEMON=/usr/local/bin/node
DAEMON_DIR=/opt/mootools/$SHORTNAME
DAEMON_USER=www-data

APP=service
APP_ARGS="-p $SOCKET"
APP_ENV=production

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

#
# Function that starts the daemon/service
#
do_start() {
	# Return
	#   0 if daemon has been started
	#   1 if daemon was already running
	#   2 if daemon could not be started
	start-stop-daemon --start --quiet --pidfile $PIDFILE --chuid $DAEMON_USER --exec $DAEMON --test > /dev/null || return 1
	rm -f "$SOCKET"
	NODE_ENV="$APP_ENV" start-stop-daemon --start --quiet --background --make-pidfile --pidfile $PIDFILE --chuid $DAEMON_USER --chdir $DAEMON_DIR --exec $DAEMON -- $APP $APP_ARGS > /dev/null || return 2
}

#
# Function that stops the daemon/service
#
do_stop() {
	# Return
	#   0 if daemon has been stopped
	#   1 if daemon was already stopped
	#   2 if daemon could not be stopped
	#   other if a failure occurred
	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --exec $DAEMON
	RETVAL="$?"
	[ "$RETVAL" = 2 ] && return 2
	rm -f "$PIDFILE" "$SOCKET"
	return "$RETVAL"
}

#
# Function that sends a SIGUSR2 to the daemon/service
#
do_reload_logs() {
	# Return
	#   0 if the signal was sent
	#   1 if the signal could not be sent
	start-stop-daemon --stop --signal USR2 --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null || return 1
	start-stop-daemon --stop --signal USR2 --quiet --pidfile $PIDFILE --exec $DAEMON
	return 0
}

#
# Function that sends a SIGHUP to the daemon/service
#
do_reload() {
	# Return
	#   0 if the signal was sent (and old socket was removed)
	#   1 if the signal could not be sent
	start-stop-daemon --stop --signal HUP --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null || return 1
	rm -f "$SOCKET"
	start-stop-daemon --stop --signal HUP --quiet --pidfile $PIDFILE --exec $DAEMON
	return 0
}

case "$1" in
	start)
		[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
		do_start
		case "$?" in
			0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
			2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
		esac
		;;
	stop)
		[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
		do_stop
		case "$?" in
			0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
			2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
		esac
		;;
	status)
		status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
		;;
	reload-logs)
		log_daemon_msg "Reloading logs of $DESC" "$NAME"
		do_reload_logs
		log_end_msg $?
		;;
	reload|force-reload)
		log_daemon_msg "Reloading $DESC" "$NAME"
		do_reload
		log_end_msg $?
		;;
	restart)
		log_daemon_msg "Restarting $DESC" "$NAME"
		do_stop
		case "$?" in
		  0|1)
			do_start
			case "$?" in
				0) log_end_msg 0 ;;
				1) log_end_msg 1 ;; # Old process is still running
				*) log_end_msg 1 ;; # Failed to start
			esac
			;;
		  *)
			# Failed to stop
			log_end_msg 1
			;;
		esac
		;;
	*)
		echo "Usage: $SCRIPTNAME {start|stop|status|restart|reload|reload-logs|force-reload}" >&2
		exit 3
		;;
esac

:
